### ISSUE TITLE
changing the manual path vars to $path

### ISSUE THREAD

**Issue by docrostov** [loathers/TourGuide#110]
![image](https://user-images.githubusercontent.com/8014761/213278235-1bb44b4f-2565-4ae1-a3c9-823a4b2912a0.png)
all of these can just be $path calls lol

**Comment by JamesDowney** [comment]
https://github.com/loathers/TourGuide/blob/b493ddc4ca3f155ab03384e2240ca378866dc346/Source/relay/TourGuide/Support/Statics.ash#L4-L58

**Comment by docrostov** [comment]
closing this because honestly after doing all the LoL support i have now realized that these statics actually are mildly helpful because writing $path[Legacy of Loathing] is much more prone to bugs than letting VSCode autocomplete PATH_LEGACY_OF_LOATHING for you. i am pretty sure at least 5 PRs in the LoL PR were me mispelling Legacy of Loathing in the $path call because i write tourguide code when i am tired.
