### ISSUE TITLE
move minimized tiles to low priority

### ISSUE THREAD

**Issue by docrostov** [loathers/TourGuide#118]
![A12F5FB1-E159-4ED6-BF76-052F208D0326](https://user-images.githubusercontent.com/8014761/217841802-f2880737-b5a9-4049-b9de-5ef5a9ff61f9.jpeg)

**Comment by plasticmacaroni** [comment]
Took a first stab at this here: https://github.com/loathers/TourGuide/pull/154#issue-1758161710

There are still issues, but I'd like to help with this!

**Comment by docrostov** [comment]
addressed and completed, thanks for this PR plasticmacaroni it is cool as heck!
