### ISSUE TITLE
[bug] digital key doesn't actually finish

### ISSUE THREAD

**Issue by docrostov** [loathers/TourGuide#134]
![image](https://user-images.githubusercontent.com/8014761/221392780-ec3ba7fb-51f8-4d80-b571-d4e4114f7db6.png)
i wonder if i just had a weird logic error. i couldn't actually test this because i am in a long aftercore so i had to disable some of the finishing conditions to make testing work anyway.

**Comment by cjquines** [comment]
i don't understand how __quest_state gets updated in the first place, outside of the inits. anyway, shouldn't we be setting it to finished if we've turned in the digital key?

the logic in [8-bit Realm.ash](https://github.com/loathers/TourGuide/blob/main/Source/relay/TourGuide/Quests/8-bit%20Realm.ash#L38) seems backwards; if we have the digital key or have turned it in, we should set it to finished, not the other way around
