### ISSUE TITLE
a variety of small notes and fixes after my first run of the year

### ISSUE THREAD

**Issue by docrostov** [loathers/TourGuide#143]
most of our tiles are working well and things are good!

here are a few things that came up while i was in AoSOL; some are AoSOL related and some aren't.

1. there is no wand in aosol. we should, ergo, not recommend users get a wand. almost tricked me like 3 separate times lol
2. there's a weird "empty data" state for the 8bit tile that i noticed; i had to visit the realm for mafia prefs to update and start out with black. what i should add is a catch for when the mafia pref is not populated that says it's likely vanya's but to reload 8bit and check bc the pref is weird. (one additional note -- some parts of the tile update faster than others, in a way that made no sense to me. i bet this is because it's a very pref-based tile and some of the prefs update at different cadences but i did not notice this when i was developing the tile and am weirded out that this happened in-run. notably, the "turns left in this zone" and "turns left overall" were almost always 1 off unless i refreshed tourguide. weird!)
3. if there is value in goose-duping the boss rewards, we should put a gray bullet or a goose emoji next to the boss item in the AoSOL tile. specifically, there is a ton of value in goose duping the wishbone (+100% item drop for two accessories? yes please) and the bat paw (-50 ML for bridge & +50 ML for tavern)
4. we need to add a catch for standard for the melodramedary added bullet in the desert tile; camel is out but it still shows up as a recommendation in the guide. (while doing this, we probably should add a "use these milestones" if you have milestones in your inventory.)
5. after spending a run with the rufus/phone tiles, i think they work really well and i'm not super motivated to make changes immediately. however, i do think there is some potential value in a tile that tells you if there is a zone with the monster that drops your targeted item + shadow slabs; it's a useful piece of info and i was pretty constantly checking the wiki to see if the artifact quest was meaningfully good/easy to snag by picking the right rift to jump into.
6. the CMC tile has this "# of pushes to double your pill" thing and it is nice but when it turns negative it should just say "your pill is doubled" because the - here is a little confusing

![image](https://user-images.githubusercontent.com/8014761/233882289-69c2514c-d689-4067-9a4c-04bb3c2225ce.png)

in addition to these things, i think we should do a more full-scale refactor of our everything-looks-yellow/blue/red tiles now that there are more things that interact with them. this is a bigger deal and i will probably finish out everything else in this issue, close it, and make a new issue for the ELY/B/R stuff before i do it... but i think that would be a valuable thing to do. sort of like the clover rework, just a good place for us to figure out how ezan's old scaffolding works and either remake it or use it more properly.

**Comment by docrostov** [comment]
re: cmc pushes, you are right. it seems to have major issues with lockets, which are zoneless. probably worth a mafia forum thread bc i bet that’s a simple change; if i have time today i’ll add one

**Comment by ajcoppa** [comment]
Finished up 1/3/4/5 in #144. Noting for posterity that we still need to figure out 2/6, including whether some underlying mafia changes can be made to help.

**Comment by docrostov** [comment]
closing this because i have resolved everything in #147
