### ISSUE TITLE
Extra resource hints: Floundry etc

### ISSUE THREAD

**Issue by sundayLOOKplants** [loathers/TourGuide#155]
- Mountain man is faxable, decent source of ore
- The Floundry -combat / 100% mainstat gear can create bridge parts / oil / pixels
- Patriotic eagle buff, banishes, tracking

**Comment by ajcoppa** [comment]
We do have a mountain man fax hint as well as Floundry item info – is there something specific you were looking for?

We'll add an eagle tile soon but it needs to wait for full mafia support.
