### ISSUE TITLE
monstrous boiler & screambat are non-wishable

### ISSUE THREAD

**Issue by docrostov** [loathers/TourGuide#180]
these appear as valid wish suggestions within tourguide and tourguide is wrong. however, well.
https://github.com/loathers/TourGuide/blob/09e0658b2b99da7549daad031780a74dbd49cfa7/Source/relay/TourGuide/Items%20of%20the%20Month/2017/GenieBottle.ash#L29
we already tell tourguide those aren't wishable! vinny reported that tourguide was still recommending those as wish targets, which means either SFaxGeneratePotentialWishes is broken or something else is broken. i don't get why ninja assassin would properly remove itself from the target list but neither of those would. ugh. what an annoying lil bug.

**Comment by danielwhite** [comment]
A bit sheepish that I didn't catch this in #168. Was curious why it didn't work happened and have a draft in #181 that can address this.

> why ninja assassin would properly remove itself from the target list but neither of those would

Turns out each addition was manually checking the `blocked_monster` array, so it was pretty easy to miss any new additions.

**Comment by docrostov** [comment]
fixed in #181 a while back lol
