### ISSUE TITLE
[Feature]: Stop recommending white pixel generation for Digital Key

### ISSUE THREAD

**Issue by BadHorseMonkey** [loathers/TourGuide#197]
### What's the request?

Currently Tourguide recommends Wishing for Ghosts to get white pixels to speed up Digital Key.  

Unless the user is on the Exploading path, this no longer works.

Probably change line 26497 (or something like this).  I don't know if there are other cases of trying for white pixels.
 ```
       
    from:    if (!familiar_is_usable($familiar[angry jung man]) )
     
    to:        if (my_path().id == PATH_EXPLOSIONS && !familiar_is_usable($familiar[angry jung man]))

```

### Account State

None

### Your current TourGuide version

4f172d48ab126a8660431f73ebd0be792659e3fa

**Comment by docrostov** [comment]
sorry for the delay -- think this is addressed in #205 now, added a quick thing there to solve it. closing because this should be resolved as soon as that is merged, and i expect to merge it tomorrow :-)
