### ISSUE TITLE
[Bug]: weird math on niche

### ISSUE THREAD

**Issue by docrostov** [loathers/TourGuide#204]
### What's the bug?

![image](https://github.com/loathers/TourGuide/assets/8014761/a362f78e-3c2d-4833-a03a-dec918942f13)
at 36 evil it should not be approx 1 turn remaining lol

### Account State

Standard (In-Run)

### In-Game Path & Class

db in smol

### TourGuide Commit

64983390d21e38866efa4984c370ea03d9aa8fea

**Comment by Semenar** [comment]
How to reproduce: banish everyone in the Niche.
Probably a more fundamental problem that we need to correctly process the situation "if everyone is banished, then no one is".

**Comment by docrostov** [comment]
> How to reproduce: banish everyone in the Niche. Probably a more fundamental problem that we need to correctly process the situation "if everyone is banished, then no one is".

oh!!! good eye, that makes sense. pushed a semi-fix in #205. it only handles the trivial olfaction case but should be easy-ish to add nosy nose et al, i just don't know how mafia stores those offhand.

**Comment by Semenar** [comment]
> > oh!!! good eye, that makes sense. pushed a semi-fix in #205. it only handles the trivial olfaction case but should be easy-ish to add nosy nose et al, i just don't know how mafia stores those offhand.

Actually, you did not even need to handle olfaction because Mafia has native support for the rates of sniffed banished monsters. So, it should be completely fixed now.
