### ISSUE TITLE
[Feature]: candy cane sword cane tile

### ISSUE THREAD

**Issue by docrostov** [loathers/TourGuide#212]
### What's the request?

just need to make a tile. according to ryo mafia prefs will be instituted soon. TES might make a tile but if this doesn't exist in a week i should just make one probs.

### Account State

All account states would benefit equally!

**Comment by uthuluc** [comment]
preliminary tile available 
https://github.com/loathers/TourGuide/compare/tes-candy-cane-sword-cane

**Comment by docrostov** [comment]
merged to main
