### ISSUE TITLE
[Feature]: desired monster to farm instead default by  garbo

### ISSUE THREAD

**Issue by exceliorxtreme** [loathers/TourGuide#238]
### What's the request?

i dont know how  can be to get an option to farm a desired monster like Clod_hopper or Swarm of fudgewasps or some like

### Account State

Aftercore

**Comment by Semenar** [comment]
Sir, this is a ~~Wendy's~~ TourGuide repository. Are you sure you did not want to send it to [garbage-collector](https://github.com/loathers/garbage-collector/issues) instead?

**Comment by exceliorxtreme** [comment]
ouch , sorry
